fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "3.2.1"
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt"
      ref: "1.5.2"
    epel:
      repo: "git://github.com/stahnma/puppet-module-epel"
      ref: "1.0.0"
  symlinks:
    omd: "#{source_dir}"
