language: ruby
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - "2.1.1"
script: bundle exec rake all
branches:
  only:
    - master
env:
  - PUPPET_VERSION=3.7.1
  - PUPPET_VERSION=4.3.1
matrix:
  fast_finish: true
  exclude:
    - rvm: "1.8.7"
      env: PUPPET_VERSION=4.3.1
